name: Links

on:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"  # Har din shaam 6 baje (UTC)

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Issue create karne ke liye permission

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --fail-if-empty=false .
          fail: false

      - name: Create GitHub Issue From Link Report
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: "🔗 Link Checker Report"
          content-filepath: ./lychee/out.md
          labels: report, automated issue
